version: '3.8'
services:
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - 8000:8000
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /data
    volumes:
      - $PWD/dynamodb/data:/data
    networks:
      - cdk-sample

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:latest
    container_name: dynamodb-admin
    tty: true
    environment:
      DYNAMO_ENDPOINT: http://dynamodb-local:8000
    ports:
      - 8001:8001
    depends_on:
      - dynamodb-local
    networks:
      - cdk-sample
networks:
  cdk-sample:
    external: true
